### ISSUE TITLE
Parallel Entity Tracking problems

### ISSUE THREAD

**Issue by Xayanix** [Imanity-Software/ImanitySpigot3-git#204]
### Expected behavior

Entities should work like on vanilla.

### Observed/Actual behavior

Entities are sometimes disappearing:
![image](https://github.com/Imanity-Software/ImanitySpigot3-git/assets/12672902/fb262594-fa08-4d30-8f34-81984163e6a4)

### Steps/models to reproduce

Make a lot holograms for example

### Plugin list

Holographic Displays

### ImanitySpigot3 version

2023.04.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by Xayanix** [comment]
After last update (today) bug occurs even with disabled parrael tracking
